[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dev"
version = "0.0.0"
description = "Internal development utilities for richio research"

[tool.setuptools.packages.find]
where = ["."]
include = ["dev"]
